# Generated by Django 4.2.6 on 2023-10-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('review_type', models.BooleanField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='img',
            field=models.ImageField(upload_to='static/movies/'),
        ),
    ]
