# Generated by Django 4.2.6 on 2023-10-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_reviews_alter_movies_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='likes',
        ),
    ]
